require("vtothek.plugins-setup")
require("vtothek.core.options")
require("vtothek.core.keymaps")
require("vtothek.core.colorscheme")
require("vtothek.plugins.nvim-tree")
require("vtothek.plugins.telescope")
require("vtothek.plugins.nvim-cmp")
require("vtothek.plugins.lsp.mason")
